### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by cryptocoinserver**
- sourcery AI optimizations to improve code quality
- pyupgrade to update to python 3.6 code version
- old .format() to new f-strings.

Besides code quality these changes also improve speed in some cases

### CODE REVIEW

**Comment by hmomin** [comment]
Hi Markus, thanks for the contribution!

I'd like to hear what the other reviewers have to say, but this looks like wayyy too many commits for a single pull request. I know sourcery gives automatic suggestions here and there to improve code quality, but many of these commits could have been merged into a single one.

For example, I'm counting at least five `replace list() with []` - all of these could have been a single commit.

Thanks again, waiting on more senior reviewers to provide input...

**Comment by hmomin** [comment]
The benefit of having less commits in a single pull request is we are actively updating the project very frequently. With small incremental changes, there's less chance of conflicting changes between developers.

**Comment by cryptocoinserver** [comment]
Hey there. That's because I manually checked whether the changes really don't change anything in terms of function before committing, and so the reason for the changes can be understood in detail. You are right though, that I could have grouped a little more.

**Comment by XiaoYangLiu-FinRL** [comment]
May be we can merge this one as early as possible?
For later ones, try to have a few commits in each PR. Thanks very much!

**Pull request merged**
