### PR TITLE
isaac gym files not need to save in envs folder

### PR DESCRIPTION
**Pull request by Yonv1943**
isaac gym files **not need to** save in envs folder. So I remove the following folders in `elegantrl/envs/`:
- `isaac_assets`
- `isaac_config`
- `isaac_tasks`
- `utils`  (isaac gym)

### CODE REVIEW

**Comment by supersglzc** [comment]
I think IsaacGym provides the simulation APIs, but those IsaacGym environments (benchmark tasks) are from the repo [IsaacGymEnvs](https://github.com/NVIDIA-Omniverse/IsaacGymEnvs). For example, the environment files and configs are stored in the task and cfg folders in IsaacGymEnvs. 

If you remove those files in ElegantRL, we should provide a way to help users create those tasks by installing IsaacGymEnvs. Here are some ideas:
1. To create an environment, we can import the task class from IsaacGymEnvs and provide a function like:

```
from isaacgymenvs.tasks import isaacgym_task_map
from omegaconf import OmegaConf

def create_task_env(cfg):
    task_cfg = OmegaConf.to_container(cfg.task, resolve=True, throw_on_missing=True)
    env = isaacgym_task_map[cfg.task.name](
        cfg=task_cfg,
        rl_device=cfg.rl_device,
        sim_device=cfg.sim_device,
        graphics_device_id=cfg.graphics_device_id,
        headless=cfg.headless,
        virtual_screen_capture=False,
        force_render=not cfg.headless
    )
    env = EnvWrapper(env)
    return env
```
2. Note that we need to provide a wrapper similar to what we have right now.
3. To obtain the cfg file, we can either keep a folder for this (like what we currently have) or use hydra searchpath to search the cfg in IsaacGymEnvs.
```
hydra:
  searchpath:
    - pkg://isaacgymenvs/cfg
```

What do you guys think:>

**Comment by Yonv1943** [comment]
> I think IsaacGym provides the simulation APIs, but those IsaacGym environments (benchmark tasks) are from the repo [IsaacGymEnvs](https://github.com/NVIDIA-Omniverse/IsaacGymEnvs). For example, the environment files and configs are stored in the task and cfg folders in IsaacGymEnvs.
> 
> If you remove those files in ElegantRL, we should provide a way to help users create those tasks by installing IsaacGymEnvs. Here are some ideas:
> 
> 1. To create an environment, we can import the task class from IsaacGymEnvs and provide a function like:
> 
> ```
> from isaacgymenvs.tasks import isaacgym_task_map
> from omegaconf import OmegaConf
> 
> def create_task_env(cfg):
>     task_cfg = OmegaConf.to_container(cfg.task, resolve=True, throw_on_missing=True)
>     env = isaacgym_task_map[cfg.task.name](
>         cfg=task_cfg,
>         rl_device=cfg.rl_device,
>         sim_device=cfg.sim_device,
>         graphics_device_id=cfg.graphics_device_id,
>         headless=cfg.headless,
>         virtual_screen_capture=False,
>         force_render=not cfg.headless
>     )
>     env = EnvWrapper(env)
>     return env
> ```
> 
> 2. Note that we need to provide a wrapper similar to what we have right now.
> 3. To obtain the cfg file, we can either keep a folder for this (like what we currently have) or use hydra searchpath to search the cfg in IsaacGymEnvs.
> 
> ```
> hydra:
>   searchpath:
>     - pkg://isaacgymenvs/cfg
> ```
> 
> What do you guys think:>

OK. `EnvWrapper` is a better way.

**Comment by Yonv1943** [comment]
https://isaac-orbit.github.io/

for back up

**Comment by LyuJZ** [comment]
> I think IsaacGym provides the simulation APIs, but those IsaacGym environments (benchmark tasks) are from the repo [IsaacGymEnvs](https://github.com/NVIDIA-Omniverse/IsaacGymEnvs). For example, the environment files and configs are stored in the task and cfg folders in IsaacGymEnvs.
> 
> If you remove those files in ElegantRL, we should provide a way to help users create those tasks by installing IsaacGymEnvs. Here are some ideas:
> 
> 1. To create an environment, we can import the task class from IsaacGymEnvs and provide a function like:
> 
> ```
> from isaacgymenvs.tasks import isaacgym_task_map
> from omegaconf import OmegaConf
> 
> def create_task_env(cfg):
>     task_cfg = OmegaConf.to_container(cfg.task, resolve=True, throw_on_missing=True)
>     env = isaacgym_task_map[cfg.task.name](
>         cfg=task_cfg,
>         rl_device=cfg.rl_device,
>         sim_device=cfg.sim_device,
>         graphics_device_id=cfg.graphics_device_id,
>         headless=cfg.headless,
>         virtual_screen_capture=False,
>         force_render=not cfg.headless
>     )
>     env = EnvWrapper(env)
>     return env
> ```
> 
> 2. Note that we need to provide a wrapper similar to what we have right now.
> 3. To obtain the cfg file, we can either keep a folder for this (like what we currently have) or use hydra searchpath to search the cfg in IsaacGymEnvs.
> 
> ```
> hydra:
>   searchpath:
>     - pkg://isaacgymenvs/cfg
> ```
> 
> What do you guys think:>

Is the env wrapper ready now?

**Pull request merged**
